<a href="https://colab.research.google.com/github/akshitgupta29/DS-ML/blob/master/Imputations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv("/content/consolidated_data_20200617.csv", thousands=r',')
data.drop('Panel_Status,Panel_Execution_Time,DCS_Status,DCS_Execution_Time,CDR_Success,CDR_Failed,CDR_Total,Benefit_Success,Benefit_Failed,Benefit_Total,Proactive_SMS_Success,Proactive_SMS_Failed,Proactive_SMS_Total,Extracts_Ready,hive-load-logs,hive-load-aggregations,hive-load-decisioning,hive-load-facts,hive-load-metadata,hive-load-panels,hive-high_priority_panels,hive-load-runtime_audit,hive-load-retention,move-roots', axis=1, inplace=True)
data.head()

Account Effecttive_date  ... hive-load-retention move-roots
0    PLDT  2020-03-30.csv  ...                   0          0
1    PLDT  2019-10-03.csv  ...                   0          0
2    PLDT  2019-09-18.csv  ...                   0          0
3    PLDT  2019-09-25.csv  ...                   0          0
4    PLDT  2019-09-06.csv  ...                   0          0

[5 rows x 26 columns]

In [ ]:
data['DCS_Execution_Time'].replace("None", np.NaN, inplace=True)

In [ ]:
data.head()

Account Effecttive_date  ... hive-load-retention move-roots
0    PLDT  2020-03-30.csv  ...                   0          0
1    PLDT  2019-10-03.csv  ...                   0          0
2    PLDT  2019-09-18.csv  ...                   0          0
3    PLDT  2019-09-25.csv  ...                   0          0
4    PLDT  2019-09-06.csv  ...                   0          0

[5 rows x 26 columns]

In [ ]:
data['DCS_Execution_Time'].unique()

array([nan, '17:32.2', '29:43.9', '14:38.1', '43:32.4', '36:42.8',
       '00:29.2', '52:49.0', '52:42.8', '45:38.1', '13:58.2', '38:42.9',
       '16:21.1', '27:18.9', '34:42.6', '31:42.9', '08:18.7', '47:42.7',
       '18:19.1', '49:42.8', '55:18.4', '00:34.8', '51:42.8', '08:47.9',
       '32:42.7', '18:21.4', '47:03.9', '33:25.1', '33:57.9', '37:42.8',
       '28:47.6', '32:42.8', '39:42.8', '08:01.0', '26:40.1', '36:47.6',
       '18:34.5', '40:42.8', 'NOT_STARETD', '17:30.4', '01:24.5',
       '43:42.9', '35:42.5', '48:16.6', '25:18.8', '57:50.7', '39:47.5',
       '27:47.6', '49:02.2', '52:01.5', '27:26.4', '21:28.2', '36:02.2',
       '09:29.2', '16:21.5', '08:32.0', '28:47.5', '16:27.6', '23:13.3',
       '36:01.7', '12:56.2', '55:47.9', '49:16.4', '43:24.1', '02:10.9',
       '16:57.7', '16:57.1', '26:25.3', '36:42.9', '38:42.7', '06:51.0',
       '37:21.5', '34:42.5', '39:42.7', '09:27.1', '35:47.6', '50:42.7',
       '08:53.2', '23:21.2', '19:12.8', '15:14.8', '02:54.4', '5

In [ ]:
data['DCS_Execution_Time'] = data['DCS_Execution_Time'].replace('NOT_STARETD', np.nan)

In [ ]:
data['DCS_Execution_Time'].head(10)

0        NaN
1    17:32.2
2    29:43.9
3    14:38.1
4    43:32.4
5        NaN
6        NaN
7        NaN
8    36:42.8
9        NaN
Name: DCS_Execution_Time, dtype: object

In [ ]:
#currently working # Do not run it now.
def convert_to_sec(dhms_str):
    '''supports also format of d:h:m:s, h:m:s, m:s and s. Please supply the parameters as a string and function will return the integer values'''
    
    #if microseconhs has '.' format instead of expected ':' format
    dhms_str = dhms_str.split(".")[0]
    
    _,d,h,m,s = (':0'*10+ dhms_str).rsplit(':',4)
    # print (f"d={d}, h= {h}, m={m}, s={s}")
    # print ((':0'*10) + dhms_str)
    return (int(d)*24*60*60+int(h)*60*60+int(m)*60+int(s))

def convert_to_minute (dhms_str):
    return (convert_to_sec(dhms_str=dhms_str)/60)

def convert_to_hour (dhms_str):
    return (convert_to_sec(dhms_str)/(60*60))

def convert_to_days (dhms_str):
    return (convert_to_sec(dhms_str)/(60*60*24))

In [ ]:
data['DCS_Execution_Time'] = data['DCS_Execution_Time'].loc[data['DCS_Execution_Time'].notnull()].apply(lambda x:convert_to_sec(str(x)))

In [5]:
#updates to make the command easier to execute

def convert_time_to_sec (data1):
    '''Supply a Series (column of data1 frame). 
    Returns the column with time converted to seconds'''
    data1 = data1.loc[data1.notnull()].apply(lambda x:convert_to_sec(str(x))) 
    return data1

def convert_time_to_minute (data1):
    '''Supply a Series (column of data1 frame). 
    Returns the column with time converted to minutes'''
    data1 = data1.loc[data1.notnull()].apply(lambda x:convert_to_sec(str(x))/60) 
    return data1

def convert_time_to_hour (data1):
    '''Supply a Series (column of data frame). 
    Returns the column with time converted to hours'''
    data1 = data1.loc[data1.notnull()].apply(lambda x:convert_to_sec(str(x))/(60*60)) 
    return data1

def convert_time_to_days (data1):
    '''Supply a Series (column of data1 frame). 
    Returns the column with time converted to days'''
    data1 = data1.loc[data1.notnull()].apply(lambda x:convert_to_sec(str(x))/(60*60*24)) 
    return data1

def convert_to_sec(dhms_str):
    '''For internal use only'''
    '''supports also format of d:h:m:s, h:m:s, m:s and s. Please supply the parameters as a string and function will return the integer values'''
    
    #if microseconhs has '.' format instead of expected ':' format
    dhms_str = dhms_str.split(".")[0]
    
    _,d,h,m,s = (':0'*10+ dhms_str).rsplit(':',4)
    # print (f"d={d}, h= {h}, m={m}, s={s}")
    # print ((':0'*10) + dhms_str)
    return (int(d)*24*60*60+int(h)*60*60+int(m)*60+int(s))

# def convert_to_minute (dhms_str):
#     return (convert_to_sec(dhms_str=dhms_str)/60)

# def convert_to_hour (dhms_str):
#     return (convert_to_sec(dhms_str)/(60*60))

# def convert_to_days (dhms_str):
#     return (convert_to_sec(dhms_str)/(60*60*24))

In [ ]:
data['DCS_Execution_Time'] = convert_time_to_sec(data['DCS_Execution_Time'])
data['DCS_Execution_Time'].head(10)

0       NaN
1    1052.0
2    1783.0
3     878.0
4    2612.0
5       NaN
6       NaN
7       NaN
8    2202.0
9       NaN
Name: DCS_Execution_Time, dtype: float64

In [ ]:
# data['DCS_Execution_Time'] = data['DCS_Execution_Time'].loc[data['DCS_Execution_Time'].notnull()].apply(lambda x:convert_to_sec(str(x)))

In [ ]:
data['DCS_Execution_Time']

0         NaN
1      1052.0
2      1783.0
3       878.0
4      2612.0
        ...  
271       NaN
272       NaN
273    1670.0
274     250.0
275       NaN
Name: DCS_Execution_Time, Length: 276, dtype: float64

In [ ]:
data.isnull().sum()

Account                        0
Effecttive_date                0
Panel_Status                   0
Panel_Execution_Time           0
DCS_Status                     0
DCS_Execution_Time           180
CDR_Success                    0
CDR_Failed                     0
CDR_Total                      0
Benefit_Success                0
Benefit_Failed                 0
Benefit_Total                  0
Proactive_SMS_Success          0
Proactive_SMS_Failed           0
Proactive_SMS_Total            0
Extracts_Ready                 0
hive-load-logs                 0
hive-load-aggregations         0
hive-load-decisioning          0
hive-load-facts                0
hive-load-metadata             0
hive-load-panels               0
hive-high_priority_panels      0
hive-load-runtime_audit        0
hive-load-retention            0
move-roots                     0
dtype: int64

# Imputations using Mean in our dataSet


In [ ]:
from sklearn.impute import SimpleImputer

model = SimpleImputer(strategy="mean", missing_values=np.nan)
# data['DCS_Execution_Time'] = data['DCS_Execution_Time'].reshape(-1,1)
model.fit(data[['DCS_Execution_Time']])
# model.fit(data)
imputed_data_mean = model.transform (data[["DCS_Execution_Time"]])
imputed_data_mean[:10]

array([[1787.70833333],
       [1052.        ],
       [1783.        ],
       [ 878.        ],
       [2612.        ],
       [1787.70833333],
       [1787.70833333],
       [1787.70833333],
       [2202.        ],
       [1787.70833333]])

# Imputations using Mean in our dataSet


In [ ]:
# Imputations using Mean in our dataSet
model = SimpleImputer(strategy="median", missing_values=np.nan)
# data['DCS_Execution_Time'] = data['DCS_Execution_Time'].reshape(-1,1)
model.fit(data[['DCS_Execution_Time']])
# model.fit(data)
imputed_data_mean = model.transform (data[["DCS_Execution_Time"]])
imputed_data_mean[:10]

array([[1932.],
       [1052.],
       [1783.],
       [ 878.],
       [2612.],
       [1932.],
       [1932.],
       [1932.],
       [2202.],
       [1932.]])

# Imputations using KNN in our dataset, but running KNN on single column


In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
imputer = KNNImputer(n_neighbors=3)
imputed_data = imputer.fit_transform(data[['DCS_Execution_Time']])

In [ ]:
imputed_data[:10]

array([[1787.70833333],
       [1052.        ],
       [1783.        ],
       [ 878.        ],
       [2612.        ],
       [1787.70833333],
       [1787.70833333],
       [1787.70833333],
       [2202.        ],
       [1787.70833333]])

# Imputations using KNN in our dataset, but running KNN on whole dataset


In [6]:
data_whole = data

In [7]:
data_whole.head()

Account Effecttive_date  ... hive-load-retention move-roots
0    PLDT  2020-03-30.csv  ...                   0          0
1    PLDT  2019-10-03.csv  ...                   0          0
2    PLDT  2019-09-18.csv  ...                   0          0
3    PLDT  2019-09-25.csv  ...                   0          0
4    PLDT  2019-09-06.csv  ...                   0          0

[5 rows x 26 columns]

In [8]:
data_whole.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Account                    276 non-null    object
 1   Effecttive_date            276 non-null    object
 2   Panel_Status               276 non-null    object
 3   Panel_Execution_Time       276 non-null    object
 4   DCS_Status                 276 non-null    object
 5   DCS_Execution_Time         276 non-null    object
 6   CDR_Success                276 non-null    int64 
 7   CDR_Failed                 276 non-null    int64 
 8   CDR_Total                  276 non-null    int64 
 9   Benefit_Success            276 non-null    int64 
 10  Benefit_Failed             276 non-null    int64 
 11  Benefit_Total              276 non-null    int64 
 12  Proactive_SMS_Success      276 non-null    int64 
 13  Proactive_SMS_Failed       276 non-null    int64 
 14  Proactive_

In [9]:
data_whole.drop(labels=['Account','Effecttive_date'], axis=1, inplace=True)

In [10]:
data_whole.head()

Panel_Status Panel_Execution_Time  ... hive-load-retention move-roots
0    SUCCEEDED              4:40:53  ...                   0          0
1    SUCCEEDED              1:58:31  ...                   0          0
2    SUCCEEDED              2:14:57  ...                   0          0
3    SUCCEEDED              4:22:15  ...                   0          0
4    SUCCEEDED              0:59:58  ...                   0          0

[5 rows x 24 columns]

In [11]:
data_whole = data_whole.astype({'Panel_Status':'category', 'DCS_Status':'category'})
data_whole.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype   
---  ------                     --------------  -----   
 0   Panel_Status               276 non-null    category
 1   Panel_Execution_Time       276 non-null    object  
 2   DCS_Status                 276 non-null    category
 3   DCS_Execution_Time         276 non-null    object  
 4   CDR_Success                276 non-null    int64   
 5   CDR_Failed                 276 non-null    int64   
 6   CDR_Total                  276 non-null    int64   
 7   Benefit_Success            276 non-null    int64   
 8   Benefit_Failed             276 non-null    int64   
 9   Benefit_Total              276 non-null    int64   
 10  Proactive_SMS_Success      276 non-null    int64   
 11  Proactive_SMS_Failed       276 non-null    int64   
 12  Proactive_SMS_Total        276 non-null    int64   
 13  Extracts_Ready             276 non-

In [12]:
data_whole.head()

Panel_Status Panel_Execution_Time  ... hive-load-retention move-roots
0    SUCCEEDED              4:40:53  ...                   0          0
1    SUCCEEDED              1:58:31  ...                   0          0
2    SUCCEEDED              2:14:57  ...                   0          0
3    SUCCEEDED              4:22:15  ...                   0          0
4    SUCCEEDED              0:59:58  ...                   0          0

[5 rows x 24 columns]

In [13]:
data_whole['Panel_Execution_Time'] = convert_time_to_sec(data_whole['Panel_Execution_Time'])
data_whole['Panel_Execution_Time']

0      16853
1       7111
2       8097
3      15735
4       3598
       ...  
271    15457
272    17572
273     8338
274     7783
275    17275
Name: Panel_Execution_Time, Length: 276, dtype: int64

In [14]:
data_whole['DCS_Execution_Time'].replace("None", np.NaN, inplace=True)
data_whole['DCS_Execution_Time'].unique()

array([nan, '17:32.2', '29:43.9', '14:38.1', '43:32.4', '36:42.8',
       '00:29.2', '52:49.0', '52:42.8', '45:38.1', '13:58.2', '38:42.9',
       '16:21.1', '27:18.9', '34:42.6', '31:42.9', '08:18.7', '47:42.7',
       '18:19.1', '49:42.8', '55:18.4', '00:34.8', '51:42.8', '08:47.9',
       '32:42.7', '18:21.4', '47:03.9', '33:25.1', '33:57.9', '37:42.8',
       '28:47.6', '32:42.8', '39:42.8', '08:01.0', '26:40.1', '36:47.6',
       '18:34.5', '40:42.8', 'NOT_STARETD', '17:30.4', '01:24.5',
       '43:42.9', '35:42.5', '48:16.6', '25:18.8', '57:50.7', '39:47.5',
       '27:47.6', '49:02.2', '52:01.5', '27:26.4', '21:28.2', '36:02.2',
       '09:29.2', '16:21.5', '08:32.0', '28:47.5', '16:27.6', '23:13.3',
       '36:01.7', '12:56.2', '55:47.9', '49:16.4', '43:24.1', '02:10.9',
       '16:57.7', '16:57.1', '26:25.3', '36:42.9', '38:42.7', '06:51.0',
       '37:21.5', '34:42.5', '39:42.7', '09:27.1', '35:47.6', '50:42.7',
       '08:53.2', '23:21.2', '19:12.8', '15:14.8', '02:54.4', '5

In [15]:
data_whole['DCS_Execution_Time'] = data_whole['DCS_Execution_Time'].replace('NOT_STARETD', np.nan)

In [16]:
data_whole['DCS_Execution_Time'] = convert_time_to_sec(data_whole['DCS_Execution_Time'])
data_whole['DCS_Execution_Time']

0         NaN
1      1052.0
2      1783.0
3       878.0
4      2612.0
        ...  
271       NaN
272       NaN
273    1670.0
274     250.0
275       NaN
Name: DCS_Execution_Time, Length: 276, dtype: float64

In [17]:
data_whole.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype   
---  ------                     --------------  -----   
 0   Panel_Status               276 non-null    category
 1   Panel_Execution_Time       276 non-null    int64   
 2   DCS_Status                 276 non-null    category
 3   DCS_Execution_Time         96 non-null     float64 
 4   CDR_Success                276 non-null    int64   
 5   CDR_Failed                 276 non-null    int64   
 6   CDR_Total                  276 non-null    int64   
 7   Benefit_Success            276 non-null    int64   
 8   Benefit_Failed             276 non-null    int64   
 9   Benefit_Total              276 non-null    int64   
 10  Proactive_SMS_Success      276 non-null    int64   
 11  Proactive_SMS_Failed       276 non-null    int64   
 12  Proactive_SMS_Total        276 non-null    int64   
 13  Extracts_Ready             276 non-

In [18]:
data_whole1 = pd.get_dummies(data = data_whole, columns=['Panel_Status', 'DCS_Status']).head()


In [31]:
data_whole1.head()
column_name = data_whole1.columns

In [32]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=3)
imputed_data = imputer.fit_transform(data_whole1)

In [33]:
print (type(imputed_data))
imputed_dataframe = pd.DataFrame(data=imputed_data, columns=column_name)
imputed_dataframe.head()

<class 'numpy.ndarray'>


Panel_Execution_Time  DCS_Execution_Time  ...  DCS_Status_New  DCS_Status_None
0               16853.0              1514.0  ...             0.0              1.0
1                7111.0              1052.0  ...             0.0              0.0
2                8097.0              1783.0  ...             0.0              0.0
3               15735.0               878.0  ...             0.0              0.0
4                3598.0              2612.0  ...             0.0              0.0

[5 rows x 29 columns]

# Imputations using MICE. 
Need a seperate package to be installed -> impyute

In [2]:
!pip install impyute

In [25]:
from impyute.imputation.cs import mice
imputed_mice = mice(data_whole1.values)

In [34]:
imputed_mice_df = pd.DataFrame(data=imputed_mice, columns=column_name)
imputed_mice_df.head()

Panel_Execution_Time  DCS_Execution_Time  ...  DCS_Status_New  DCS_Status_None
0               16853.0          701.638503  ...             0.0              1.0
1                7111.0         1052.000000  ...             0.0              0.0
2                8097.0         1783.000000  ...             0.0              0.0
3               15735.0          878.000000  ...             0.0              0.0
4                3598.0         2612.000000  ...             0.0              0.0

[5 rows x 29 columns]